---
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hetznercloud)
  exhaustive:
    default-signifies-exhaustive: true
  misspell:
    locale: "US"
  revive:
    rules:
      - name: var-naming
        disabled: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gci
    - gocritic
    - gofmt
    - goimports
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
