# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# See http://goreleaser.com
# version: 1

builds:
  - id: build
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X {{ .ModulePath }}/version.Version={{ .Version }}
      - -X {{ .ModulePath }}/version.VersionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
    binary: >-
      {{- if .IsSnapshot -}}
      {{ replace .ProjectName "-" "_" }}_{{ .Os }}_{{ .Arch }}
      {{- else -}}
      {{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}
      {{- end -}}

    targets:
      - linux_386
      - linux_amd64_v1
      - linux_arm_6
      - linux_arm64
      - freebsd_386
      - freebsd_amd64_v1
      - freebsd_arm
      - netbsd_386
      - netbsd_amd64_v1
      - netbsd_arm
      - openbsd_386
      - openbsd_amd64_v1
      - openbsd_arm
      - solaris_amd64_v1
      - darwin_amd64_v1
      - darwin_arm64
      - windows_386
      - windows_amd64_v1

snapshot:
  name_template: "{{ .Version }}-dev+{{ .ShortCommit }}"

archives:
  - format: zip
    files:
      - none*
    name_template: >-
      {{- if .IsSnapshot -}}
      {{ replace .ProjectName "-" "_" }}_{{ .Os }}_{{ .Arch }}
      {{- else -}}
      {{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}
      {{- end -}}

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - --batch
      - --local-user={{ .Env.GPG_FINGERPRINT }}
      - --output=${signature}
      - --detach-sign
      - ${artifact}
