---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^\.web-docs/.*$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks

      - id: check-json
      - id: check-yaml
      - id: check-toml

      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write --ignore-unknown
        language: node
        types: [text]
        require_serial: false
        additional_dependencies:
          - prettier@3.3.3
        files: \.(mdx?|ya?ml)$
        exclude: ^CHANGELOG.md$

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.0
    hooks:
      - id: golangci-lint-full
        args: [--timeout=5m]

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        description: Format shell scripts with shfmt
        language: golang
        additional_dependencies:
          - mvdan.cc/sh/v3/cmd/shfmt@v3.8.0
        entry: shfmt -i 2 -ci -sr -kp -w
        types: [shell]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: generate
        name: generate
        description: Generate the packer files
        language: system
        entry: make generate
        pass_filenames: false
